# Generated by Django 3.2.5 on 2021-08-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encarregado',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encarregadoEndereco', to='estudante.endereco'),
        ),
        migrations.AlterField(
            model_name='encarregado',
            name='telefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encarregadoTelefone', to='estudante.telefone'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='encarregado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudanteEncarregado', to='estudante.encarregado'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudanteEndereco', to='estudante.endereco'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='filiacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudanteFiliacoe', to='estudante.filiacao'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='telefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudanteTelefone', to='estudante.telefone'),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiacaoEndereco', to='estudante.endereco'),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='telefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiacaoTelefone', to='estudante.telefone'),
        ),
    ]
